language: go

go:
  - tip

before_install:
  # Rocksdb dependencies taken from https://github.com/tecbot/gorocksdb/blob/master/.travis.yml
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.8 libsnappy-dev zlib1g-dev libbz2-dev -qq
  - export CXX="g++-4.8" CC="gcc-4.8"
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libgflags2_2.0-1.1ubuntu1_amd64.deb
  - sudo dpkg -i libgflags2_2.0-1.1ubuntu1_amd64.deb
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libgflags-dev_2.0-1.1ubuntu1_amd64.deb
  - sudo dpkg -i libgflags-dev_2.0-1.1ubuntu1_amd64.deb
  - git clone https://github.com/facebook/rocksdb.git /tmp/rocksdb
  - pushd /tmp/rocksdb
  - make clean
  - make shared_lib
  - sudo cp --preserve=links ./librocksdb.* /usr/lib/
  - sudo cp -r ./include/rocksdb/ /usr/include/
  - popd
